CREATE TABLE members (
kullanici_id SERIAL PRIMARY KEY,
kullanici_adi varchar(50) UNIQUE NOT NULL,
email varchar(100) UNIQUE NOT NULL,
sifre varchar(255) NOT NULL,
kayit_tarihi TIMESTAMP DEFAULT CURRENT_DATE,
Ad varchar(50),
soyad varchar(50)
);

CREATE TABLE EGITIMLER(
EGITIM_ID SERIAL PRIMARY KEY,
ADI VARCHAR(200) NOT NULL,
ACIKLAMASI TEXT,
BASLANGIC_TARIHI DATE,
BITIS_TARIHI DATE,
EGITMEN_BILGISI VARCHAR(100),
KATEGORI_ID INTEGER,
FOREIGN KEY (KATEGORI_ID) REFERENCES KATEGORILER(KATEGORI_ID)
)

CREATE TABLE KATEGORILER(
KATEGORI_ID SERIAL PRIMARY KEY,
KATEGORI_ADI VARCHAR(100) NOT NULL
);

INSERT INTO kategoriler (kategori_adi) VALUES 
('yapayzeka')
('blokzincir'),
('siber güvenlik');

CREATE TABLE KATILIMLAR(
KATILIM_ID SERIAL PRIMARY KEY,
KULLANICI_ID INTEGER NOT NULL,
EGITIM_ID INTEGER NOT NULL,
KATILIM_TARIHI TIMESTAMP DEFAULT CURRENT_DATE,
FOREIGN KEY (KULLANICI_ID) REFERENCES MEMBERS(KULLANICI_ID),
FOREIGN KEY (EGITIM_ID) REFERENCES EGITIMLER (EGITIM_ID)
);

CREATE TABLE SERTIFIKALAR(
SERTIFIKA_ID SERIAL PRIMARY KEY NOT NULL,
SERTIFIKA_KODU VARCHAR(100) UNIQUE NOT NULL,
VERILIS_TARIHI DATE 
);

CREATE TABLE SERTIFIKA_ATAMALARI(
ATAMA_ID SERIAL PRIMARY KEY,
KULLANICI_ID INTEGER NOT NULL,
EGITIM_ID INTEGER NOT NULL,
SERTIFIKA_ID INTEGER NOT NULL,
ALIM_TARIHI DATE,
FOREIGN KEY (KULLANICI_ID) REFERENCES MEMBERS(KULLANICI_ID),
FOREIGN KEY (EGITIM_ID) REFERENCES EGITIMLER(EGITIM_ID ),
FOREIGN KEY (SERTIFIKA_ID) REFERENCES SERTIFIKALAR(SERTIFIKA_ID)
);

CREATE TABLE BLOG_GONDERILERI(
GONDERI_ID SERIAL PRIMARY KEY,
BASLIK VARCHAR(255) NOT NULL,
ICERIK TEXT ,
YAYIN_TARIHI TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
YAZAR_ID INTEGER NOT NULL,
YAZAR_ADI VARCHAR(50),
FOREIGN KEY (YAZAR_ID) REFERENCES MEMBERS(KULLANICI_ID)
);
